# Generated by Django 5.2.13 on 2026-06-06 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='client_logos/')),
                ('website_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Logo de Cliente',
                'verbose_name_plural': 'Logos de Clientes',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line1', models.CharField(blank=True, help_text='Primera línea del título sobre el video (dejar en blanco para ocultar)', max_length=200)),
                ('title_line2', models.CharField(blank=True, help_text='Segunda línea del título', max_length=200)),
                ('video_file', models.FileField(blank=True, help_text='Subir MP4 aquí (Cloudinary en producción). Tiene prioridad sobre la URL.', upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='URL externa de CDN para el video. Usar si no se sube el archivo directamente.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Video Hero',
                'verbose_name_plural': 'Videos Hero',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('label_en', models.CharField(blank=True, help_text='Etiqueta en inglés (opcional)', max_length=100)),
                ('url', models.CharField(help_text='Usar #seccionId para anclas internas', max_length=200)),
                ('section_group', models.CharField(choices=[('proyectos', 'PROYECTOS'), ('publicaciones', 'PUBLICACIONES'), ('herramientas', 'HERRAMIENTAS'), ('contacto', 'CONTACTO')], default='proyectos', max_length=30)),
                ('filter_value', models.CharField(blank=True, help_text='Valor de data-filter para filtrado de portafolio (ej: CASAS, EDUCACIÓN). Dejar vacío si no filtra.', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ítem de Menú',
                'verbose_name_plural': 'Ítems de Menú',
                'ordering': ['section_group', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre en filtros (ej: CASAS, EDUCACIÓN)', max_length=100)),
                ('name_en', models.CharField(blank=True, help_text='Nombre en inglés', max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Portafolio',
                'verbose_name_plural': 'Categorías de Portafolio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='MSRAA — Estudio de Arquitectura', max_length=200)),
                ('tagline', models.CharField(default='MSRAA', max_length=200)),
                ('color_gold', models.CharField(default='#e8b84b', help_text='Color dorado en tema oscuro (CSS --gold). Ej: #e8b84b', max_length=20)),
                ('color_gold_light', models.CharField(default='#b8841a', help_text='Color dorado en tema claro. Ej: #b8841a', max_length=20)),
                ('font_size_base', models.PositiveIntegerField(default=16, help_text='Tamaño base de fuente en px (12–24)', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(24)])),
                ('font_family', models.CharField(default='Calibri, sans-serif', max_length=100)),
                ('contact_email', models.EmailField(default='contacto@msraa.cl', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('logo_main', models.ImageField(blank=True, help_text='Logo principal MSRAA (PNG con transparencia). Dejar en blanco para usar el logo estático por defecto.', upload_to='logos/')),
                ('about_label', models.CharField(default='SOBRE EL PROYECTO', max_length=100)),
                ('about_p1', models.TextField(default='Cuatro volúmenes dibujan su órbita en torno a un vacío central que actúa como corazón del proyecto. La luz natural penetra desde múltiples ángulos, creando una danza de sombras que transforma el espacio a lo largo del día.')),
                ('about_p2', models.TextField(default='Las fachadas están marcadas por una rigurosa modulación que refleja la precisión técnica del proceso constructivo. Cada detalle ha sido pensado para que la obra dialogue con su entorno y perdure en el tiempo.')),
                ('stat1_number', models.PositiveIntegerField(default=50)),
                ('stat1_prefix', models.CharField(default='Proyectos', max_length=50)),
                ('stat1_label', models.CharField(default='Instalaciones completadas', max_length=100)),
                ('stat2_number', models.PositiveIntegerField(default=10)),
                ('stat2_prefix', models.CharField(default='Difusión', max_length=50)),
                ('stat2_label', models.CharField(default='Publicaciones especializadas', max_length=100)),
                ('stat3_number', models.PositiveIntegerField(default=300)),
                ('stat3_prefix', models.CharField(default='Superficie construida', max_length=50)),
                ('stat3_label', models.CharField(default='M² construidos en todo Chile', max_length=100)),
                ('trust_lbl', models.CharField(default='QUIENES NOS HAN CONFIADO SU VISIÓN', max_length=200)),
                ('trust_title', models.CharField(default='ORGULLOSOS DE CADA COLABORACIÓN', max_length=200)),
                ('trust_sub', models.TextField(default='Agradecemos profundamente la confianza de nuestros clientes, cuya visión y colaboración han sido fundamentales para crear proyectos que transforman espacios y comunidades.')),
                ('footer_copy', models.CharField(default='© 2026 MSRAA ESTUDIO DE ARQUITECTURA', max_length=200)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('hero_image', models.ImageField(blank=True, help_text='Imagen principal del proyecto (se muestra en la grilla)', upload_to='portfolio/heroes/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.portfoliocategory')),
            ],
            options={
                'verbose_name': 'Proyecto de Portafolio',
                'verbose_name_plural': 'Proyectos de Portafolio',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/images/')),
                ('size', models.CharField(choices=[('large', 'Grande'), ('small', 'Pequeña')], default='large', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.portfolioproject')),
            ],
            options={
                'verbose_name': 'Imagen de Proyecto',
                'verbose_name_plural': 'Imágenes de Proyecto',
                'ordering': ['order'],
            },
        ),
    ]
