# Generated by Django 5.2.13 on 2026-06-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_sidebar_color',
            field=models.CharField(default='#CC0000', help_text='Color del logo izquierdo pequeño (ej: #CC0000 = rojo oficial)', max_length=20, verbose_name='Color logo sidebar'),
        ),
    ]
