# Generated by Django 5.2.13 on 2026-06-07 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration_logo_sidebar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogo',
            name='display_scale',
            field=models.PositiveIntegerField(default=100, help_text='Tamaño visual del logo (50–200%). Default 100. Subir si logo aparece pequeño.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)], verbose_name='Escala %'),
        ),
    ]
