# Generated by Django 5.2.13 on 2026-06-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clientlogo_display_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='section_group',
            field=models.CharField(choices=[('proyectos', 'PROYECTOS'), ('publicaciones', 'PUBLICACIONES'), ('curriculum', 'CURRICULUM'), ('herramientas', 'HERRAMIENTAS'), ('contacto', 'CONTACTO')], default='proyectos', max_length=30),
        ),
    ]
