# Generated by Django 5.2.13 on 2026-06-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_curriculum_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('formacion', 'FORMACIÓN'), ('experiencia', 'EXPERIENCIA'), ('reconocimientos', 'RECONOCIMIENTOS'), ('publicaciones', 'PUBLICACIONES'), ('otros', 'OTROS')], default='experiencia', max_length=30, verbose_name='Categoría')),
                ('year', models.CharField(blank=True, help_text='Ej: 2020, 2015 — 2020, 2010 —', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo / Institución')),
                ('url', models.URLField(blank=True, help_text='Enlace externo (Dropbox, Drive, web). Dejar vacío si no aplica.')),
                ('url_label', models.CharField(blank=True, default='Ver documento', help_text='Texto del enlace', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ítem de Curriculum',
                'verbose_name_plural': 'Ítems de Curriculum',
                'ordering': ['category', 'order'],
            },
        ),
    ]
