# Generated by Django 5.2.13 on 2026-06-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_curriculum_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('noticia', 'NOTICIA'), ('charla', 'CHARLA'), ('premio', 'PREMIO'), ('publicacion', 'PUBLICACIÓN'), ('entrevista', 'ENTREVISTA'), ('otro', 'OTRO')], default='noticia', max_length=20, verbose_name='Tipo')),
                ('year', models.CharField(blank=True, help_text='Ej: 2024', max_length=10, verbose_name='Año')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('url', models.URLField(blank=True, help_text='Dropbox, artículo, video, etc.', verbose_name='Enlace')),
                ('url_label', models.CharField(blank=True, default='Ver más', max_length=60, verbose_name='Texto del enlace')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ítem de Medios',
                'verbose_name_plural': 'Ítems de Medios',
                'ordering': ['-year', 'order'],
            },
        ),
    ]
