# Generated by Django 5.2.13 on 2026-06-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_media_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto portada del ítem (recomendado 1200×800px)', null=True, upload_to='medios/', verbose_name='Imagen'),
        ),
    ]
