# Generated by Django 5.2.13 on 2026-06-14 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_media_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medios/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.mediaitem')),
            ],
            options={
                'verbose_name': 'Imagen referencial',
                'verbose_name_plural': 'Imágenes referenciales',
                'ordering': ['order'],
            },
        ),
    ]
