# Generated by Django 5.2.13 on 2026-06-14 17:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_media_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube o Vimeo. Ej: https://youtu.be/xxxx', verbose_name='URL de video'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_label',
            field=models.CharField(default='SOBRE EL PROYECTO', max_length=100, verbose_name='Etiqueta sección Sobre'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_p1',
            field=models.TextField(default='Cuatro volúmenes dibujan su órbita en torno a un vacío central que actúa como corazón del proyecto. La luz natural penetra desde múltiples ángulos, creando una danza de sombras que transforma el espacio a lo largo del día.', verbose_name='Párrafo 1 (Sobre)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_p2',
            field=models.TextField(default='Las fachadas están marcadas por una rigurosa modulación que refleja la precisión técnica del proceso constructivo. Cada detalle ha sido pensado para que la obra dialogue con su entorno y perdure en el tiempo.', verbose_name='Párrafo 2 (Sobre)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='color_gold',
            field=models.CharField(default='#e8b84b', help_text='Color dorado en tema oscuro (CSS --gold). Ej: #e8b84b', max_length=20, verbose_name='Color dorado'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='color_gold_light',
            field=models.CharField(default='#b8841a', help_text='Color dorado en tema claro. Ej: #b8841a', max_length=20, verbose_name='Color dorado claro'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_email',
            field=models.EmailField(default='contacto@msraa.cl', max_length=254, verbose_name='Correo de contacto'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='font_family',
            field=models.CharField(default='Calibri, sans-serif', max_length=100, verbose_name='Familia tipográfica'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='font_size_base',
            field=models.PositiveIntegerField(default=16, help_text='Tamaño base de fuente en px (12–24)', validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(24)], verbose_name='Tamaño de fuente base'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_copy',
            field=models.CharField(default='© 2026 MSRAA ESTUDIO DE ARQUITECTURA', max_length=200, verbose_name='Texto pie de página'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='URL Instagram'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='URL LinkedIn'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_main',
            field=models.ImageField(blank=True, help_text='Logo principal MSRAA (PNG con transparencia). Dejar en blanco para usar el logo estático por defecto.', upload_to='logos/', verbose_name='Logo principal'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_title',
            field=models.CharField(default='MSRAA — Estudio de Arquitectura', max_length=200, verbose_name='Título del sitio'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat1_label',
            field=models.CharField(default='Instalaciones completadas', max_length=100, verbose_name='Estadística 1 — etiqueta'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat1_number',
            field=models.PositiveIntegerField(default=50, verbose_name='Estadística 1 — número'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat1_prefix',
            field=models.CharField(default='Proyectos', max_length=50, verbose_name='Estadística 1 — prefijo'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat2_label',
            field=models.CharField(default='Publicaciones especializadas', max_length=100, verbose_name='Estadística 2 — etiqueta'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat2_number',
            field=models.PositiveIntegerField(default=10, verbose_name='Estadística 2 — número'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat2_prefix',
            field=models.CharField(default='Difusión', max_length=50, verbose_name='Estadística 2 — prefijo'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat3_label',
            field=models.CharField(default='M² construidos en todo Chile', max_length=100, verbose_name='Estadística 3 — etiqueta'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat3_number',
            field=models.PositiveIntegerField(default=300, verbose_name='Estadística 3 — número'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stat3_prefix',
            field=models.CharField(default='Superficie construida', max_length=50, verbose_name='Estadística 3 — prefijo'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='tagline',
            field=models.CharField(default='MSRAA', max_length=200, verbose_name='Eslogan'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='trust_lbl',
            field=models.CharField(default='QUIENES NOS HAN CONFIADO SU VISIÓN', max_length=200, verbose_name='Colaboradores — etiqueta'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='trust_sub',
            field=models.TextField(default='Agradecemos profundamente la confianza de nuestros clientes, cuya visión y colaboración han sido fundamentales para crear proyectos que transforman espacios y comunidades.', verbose_name='Colaboradores — subtítulo'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='trust_title',
            field=models.CharField(default='ORGULLOSOS DE CADA COLABORACIÓN', max_length=200, verbose_name='Colaboradores — título'),
        ),
        migrations.CreateModel(
            name='CurriculumItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='curriculum/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Pie de foto')),
                ('order', models.PositiveIntegerField(default=0)),
                ('curriculum_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.curriculumitem')),
            ],
            options={
                'verbose_name': 'Imagen de Curriculum',
                'verbose_name_plural': 'Imágenes de Curriculum',
                'ordering': ['order'],
            },
        ),
    ]
