# Generated by Django 5.2.13 on 2026-06-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_curriculumitem_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube o Vimeo. Ej: https://youtu.be/xxxx — se muestra como panel en el overlay', verbose_name='URL de video'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.portfoliocategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imagen portada (se muestra en la grilla)', upload_to='portfolio/heroes/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='year',
            field=models.CharField(max_length=10, verbose_name='Año'),
        ),
    ]
