# Generated by Django 5.2.13 on 2026-06-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_portfolioproject_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo o Cloudinary player. Ej: https://player.cloudinary.com/embed/?cloud_name=xxx&public_id=yyy', verbose_name='URL de video'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='url',
            field=models.URLField(blank=True, help_text='Dropbox, artículo, web, etc.', verbose_name='Enlace'),
        ),
    ]
