# Generated by Django 5.2.13 on 2026-06-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mediaitem_video_url_alter_mediaitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumitemimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL directa, Dropbox o Drive (alternativa a subir archivo)', verbose_name='URL de imagen'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL directa o Dropbox/Drive para la imagen portada (tiene prioridad sobre la imagen subida)', verbose_name='URL de imagen'),
        ),
        migrations.AddField(
            model_name='mediaitemimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL directa, Dropbox o Drive (alternativa a subir archivo)', verbose_name='URL de imagen'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='URL directa, Dropbox o Drive para la imagen portada (tiene prioridad sobre la imagen subida)', verbose_name='URL imagen principal'),
        ),
        migrations.AddField(
            model_name='portfolioprojectimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL directa, Dropbox o Drive (alternativa a subir archivo)', verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='curriculumitemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='curriculum/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto portada subida al servidor', null=True, upload_to='medios/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='mediaitemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medios/gallery/'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imagen portada subida al servidor', upload_to='portfolio/heroes/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='portfolioprojectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/images/'),
        ),
    ]
