# Generated by Django 5.2.13 on 2026-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_curriculumitemimage_image_url_mediaitem_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlogo',
            name='image',
            field=models.ImageField(max_length=500, upload_to='client_logos/'),
        ),
        migrations.AlterField(
            model_name='curriculumitemimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='curriculum/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto portada subida al servidor', max_length=500, null=True, upload_to='medios/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='mediaitemimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='medios/gallery/'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imagen portada subida al servidor', max_length=500, upload_to='portfolio/heroes/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='portfolioprojectimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_main',
            field=models.ImageField(blank=True, help_text='Logo principal MSRAA (PNG con transparencia). Dejar en blanco para usar el logo estático por defecto.', max_length=500, upload_to='logos/', verbose_name='Logo principal'),
        ),
    ]
