# Generated by Django 5.2.13 on 2026-06-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_clientlogo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumitem',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Subtítulo / Institución (EN)'),
        ),
        migrations.AddField(
            model_name='curriculumitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título (EN)'),
        ),
        migrations.AddField(
            model_name='curriculumitem',
            name='url_label_en',
            field=models.CharField(blank=True, help_text='Texto del enlace (EN)', max_length=60),
        ),
        migrations.AddField(
            model_name='herovideo',
            name='title_line1_en',
            field=models.CharField(blank=True, help_text='Primera línea del título (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='herovideo',
            name='title_line2_en',
            field=models.CharField(blank=True, help_text='Segunda línea del título (EN)', max_length=200),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción (EN)'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título (EN)'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='url_label_en',
            field=models.CharField(blank=True, max_length=60, verbose_name='Texto del enlace (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación (EN)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etiqueta sección Sobre (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_p1_en',
            field=models.TextField(blank=True, verbose_name='Párrafo 1 (Sobre) (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_p2_en',
            field=models.TextField(blank=True, verbose_name='Párrafo 2 (Sobre) (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_copy_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Texto pie de página (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat1_label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estadística 1 — etiqueta (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat1_prefix_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estadística 1 — prefijo (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat2_label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estadística 2 — etiqueta (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat2_prefix_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estadística 2 — prefijo (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat3_label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estadística 3 — etiqueta (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stat3_prefix_en',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estadística 3 — prefijo (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='trust_lbl_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Colaboradores — etiqueta (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='trust_sub_en',
            field=models.TextField(blank=True, verbose_name='Colaboradores — subtítulo (EN)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='trust_title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Colaboradores — título (EN)'),
        ),
    ]
