# Generated by Django 5.2.13 on 2026-07-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_contactsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumitem',
            name='url',
            field=models.URLField(blank=True, help_text='Enlace externo (Dropbox, Drive, web). Dejar vacío si no aplica.', max_length=500),
        ),
        migrations.AlterField(
            model_name='curriculumitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube o Vimeo. Ej: https://youtu.be/xxxx', max_length=500, verbose_name='URL de video'),
        ),
        migrations.AlterField(
            model_name='curriculumitemimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL directa, Dropbox o Drive (alternativa a subir archivo)', max_length=500, verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='video_file',
            field=models.FileField(blank=True, help_text='Subir MP4 (Cloudinary en producción). Prioridad sobre URL. Recomendado: 1920×1080px, H.264, máx 100MB.', upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL Dropbox, Cloudinary CDN o enlace directo MP4. Recomendado: 1920×1080px. Dropbox: copiar enlace compartido del archivo .mp4.', max_length=500),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto portada. Resolución recomendada: 800×533px (3:2).', max_length=500, null=True, upload_to='medios/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Dropbox o Drive (prioridad sobre imagen subida). Recomendado: 800×533px (3:2).', max_length=500, verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='url',
            field=models.URLField(blank=True, help_text='Dropbox, artículo, web, etc.', max_length=500, verbose_name='Enlace'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo, Cloudinary o Dropbox (MP4 directo). Ej: https://youtu.be/xxx o enlace Dropbox .mp4', max_length=500, verbose_name='URL de video'),
        ),
        migrations.AlterField(
            model_name='mediaitemimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL directa, Dropbox o Drive (alternativa a subir archivo)', max_length=500, verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Imagen portada del proyecto. Recomendado: 1600×1067px (3:2) o 1920×1080px.', max_length=500, upload_to='portfolio/heroes/', verbose_name='Imagen principal'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='hero_image_url',
            field=models.URLField(blank=True, help_text='Dropbox o Drive (prioridad sobre imagen subida). Recomendado: 1600×1067px (3:2).', max_length=500, verbose_name='URL imagen principal'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo o Dropbox MP4. Ej: https://youtu.be/xxxx — se muestra como panel en el overlay.', max_length=500, verbose_name='URL de video'),
        ),
        migrations.AlterField(
            model_name='portfolioprojectimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL directa, Dropbox o Drive (alternativa a subir archivo)', max_length=500, verbose_name='URL de imagen'),
        ),
    ]
