# Generated by Django 5.2.13 on 2026-07-01 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_url_max_length_500'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='hero_slide_duration',
            field=models.PositiveIntegerField(default=15, help_text='Segundos que se muestra cada slide del hero antes de pasar al siguiente (5–60s).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='Duración slide hero (seg)'),
        ),
    ]
