# Generated by Django 5.2.13 on 2026-07-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_mediaitemsection_mediaitemvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='img_gravity',
            field=models.CharField(blank=True, choices=[('auto', 'Automático (IA)'), ('face', 'Cara'), ('faces', 'Caras múltiples'), ('center', 'Centro'), ('north', 'Arriba'), ('south', 'Abajo'), ('east', 'Derecha'), ('west', 'Izquierda'), ('northeast', 'Arriba-Derecha'), ('northwest', 'Arriba-Izquierda'), ('southeast', 'Abajo-Derecha'), ('southwest', 'Abajo-Izquierda')], default='auto', help_text='Dónde enfocar al recortar la imagen de portada.', max_length=20, verbose_name='Punto de enfoque (imagen)'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='img_ratio',
            field=models.CharField(blank=True, choices=[('', 'Original'), ('16:9', '16:9 — Panorámico'), ('4:3', '4:3 — Clásico'), ('3:2', '3:2 — Foto'), ('1:1', '1:1 — Cuadrado'), ('2:3', '2:3 — Retrato')], default='', help_text='Recortar imagen a esta proporción. Vacío = original.', max_length=10, verbose_name='Proporción de imagen'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='img_gravity',
            field=models.CharField(blank=True, choices=[('auto', 'Automático (IA)'), ('face', 'Cara'), ('faces', 'Caras múltiples'), ('center', 'Centro'), ('north', 'Arriba'), ('south', 'Abajo'), ('east', 'Derecha'), ('west', 'Izquierda'), ('northeast', 'Arriba-Derecha'), ('northwest', 'Arriba-Izquierda'), ('southeast', 'Abajo-Derecha'), ('southwest', 'Abajo-Izquierda')], default='auto', help_text='Dónde enfocar al recortar la imagen principal.', max_length=20, verbose_name='Punto de enfoque (imagen)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='img_ratio',
            field=models.CharField(blank=True, choices=[('', 'Original'), ('16:9', '16:9 — Panorámico'), ('4:3', '4:3 — Clásico'), ('3:2', '3:2 — Foto'), ('1:1', '1:1 — Cuadrado'), ('2:3', '2:3 — Retrato')], default='', help_text='Recortar imagen a esta proporción. Vacío = original.', max_length=10, verbose_name='Proporción de imagen'),
        ),
    ]
