# Generated by Django 5.2.13 on 2026-07-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_img_crop_wh_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='summary',
            field=models.TextField(blank=True, help_text='Texto corto que aparece en la tarjeta del portafolio. Si se deja vacío se usan los primeros 280 caracteres de la descripción.', verbose_name='Resumen (tarjeta)'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='summary_en',
            field=models.TextField(blank=True, verbose_name='Resumen (tarjeta EN)'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='img_bg',
            field=models.CharField(blank=True, default='', help_text='Solo para pad. Ej: white, black, auto:border, rgb:FF0000', max_length=30, verbose_name='Color de fondo'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='img_crop',
            field=models.CharField(blank=True, choices=[('fill', 'Rellenar (c_fill) — recorta para llenar'), ('fit', 'Ajustar (c_fit) — escala sin recortar'), ('pad', 'Añadir fondo (c_pad) — letterbox/pillarbox'), ('scale', 'Estirar (c_scale) — deforma proporciones')], default='fill', help_text='fill=recorta · fit=ajusta · pad=añade fondo · scale=estira', max_length=10, verbose_name='Modo de recorte'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=models.TextField(verbose_name='Descripción completa'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descripción completa (EN)'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='img_bg',
            field=models.CharField(blank=True, default='', help_text='Solo para pad. Ej: white, black, auto:border, rgb:FF0000', max_length=30, verbose_name='Color de fondo'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='img_crop',
            field=models.CharField(blank=True, choices=[('fill', 'Rellenar (c_fill) — recorta para llenar'), ('fit', 'Ajustar (c_fit) — escala sin recortar'), ('pad', 'Añadir fondo (c_pad) — letterbox/pillarbox'), ('scale', 'Estirar (c_scale) — deforma proporciones')], default='fill', help_text='fill=recorta · fit=ajusta · pad=añade fondo · scale=estira', max_length=10, verbose_name='Modo de recorte'),
        ),
        migrations.AlterField(
            model_name='portfolioprojectimage',
            name='img_gravity',
            field=models.CharField(blank=True, choices=[('auto', 'Automático (IA)'), ('face', 'Cara'), ('faces', 'Caras múltiples'), ('center', 'Centro'), ('north', 'Arriba'), ('south', 'Abajo'), ('east', 'Derecha'), ('west', 'Izquierda'), ('northeast', 'Arriba-Derecha'), ('northwest', 'Arriba-Izquierda'), ('southeast', 'Abajo-Derecha'), ('southwest', 'Abajo-Izquierda')], default='auto', max_length=20, verbose_name='Punto de enfoque'),
        ),
        migrations.AlterField(
            model_name='portfolioprojectimage',
            name='img_ratio',
            field=models.CharField(blank=True, choices=[('', 'Original'), ('16:9', '16:9 — Panorámico'), ('4:3', '4:3 — Clásico'), ('3:2', '3:2 — Foto'), ('1:1', '1:1 — Cuadrado'), ('2:3', '2:3 — Retrato')], default='', max_length=10, verbose_name='Proporción'),
        ),
    ]
