# Generated by Django 5.2.13 on 2026-07-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_summary_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('metric', models.CharField(choices=[('storage_pct', 'Almacenamiento Cloudinary (%)'), ('bandwidth_pct', 'Ancho de banda Cloudinary (%)'), ('response_ms', 'Tiempo de respuesta sitio (ms)')], max_length=30, verbose_name='Metrica')),
                ('condition', models.CharField(choices=[('gt', '>  Mayor que'), ('lt', '<  Menor que')], default='gt', max_length=5, verbose_name='Condicion')),
                ('threshold', models.FloatField(verbose_name='Umbral')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo chequeo')),
                ('last_status', models.CharField(choices=[('ok', 'OK'), ('warn', 'Advertencia'), ('crit', 'Critico'), ('unknown', 'Sin datos')], default='unknown', max_length=10, verbose_name='Estado')),
                ('email_notify', models.EmailField(blank=True, max_length=254, verbose_name='Email notificacion')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-date', '-count'],
                'unique_together': {('date', 'path')},
            },
        ),
    ]
