# Generated by Django 6.0.7 on 2026-07-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_siteconfiguration_color_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumitem',
            name='description',
            field=models.TextField(blank=True, help_text='Texto de resumen mostrado bajo el subtítulo (ej: resumen de un documento adjunto).', verbose_name='Resumen'),
        ),
        migrations.AddField(
            model_name='curriculumitem',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Resumen (EN)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
