# Generated by Django 6.0.7 on 2026-07-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_curriculumitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumitem',
            name='subgroup',
            field=models.CharField(blank=True, help_text='Ej: "Concursos" — agrupa items bajo un subtítulo dentro de la categoría. Items con el mismo subgrupo deben quedar consecutivos (ordenar con "order"). Dejar vacío para no agrupar.', max_length=100, verbose_name='Subgrupo'),
        ),
    ]
