# Generated by Django 6.0.7 on 2026-07-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_curriculumitem_subgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='tipo',
            field=models.CharField(choices=[('noticia', 'NOTICIA'), ('charla', 'CHARLA'), ('premio', 'PREMIO'), ('concurso', 'CONCURSO'), ('publicacion', 'PUBLICACIÓN'), ('entrevista', 'ENTREVISTA'), ('otro', 'OTRO')], default='noticia', max_length=20, verbose_name='Tipo'),
        ),
    ]
