# Generated by Django 5.2.13 on 2026-07-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_curriculumitem_subgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='featured_next_project',
            field=models.ForeignKey(blank=True, help_text="Proyecto cuya foto/video grande se muestra en el banner 'EXPLORAR PROYECTO'. Vacío = se usa automáticamente el último proyecto del portafolio.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.portfolioproject', verbose_name="Proyecto destacado (banner 'Explorar Proyecto')"),
        ),
    ]
