# Generated by Django 5.2.13 on 2026-07-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_siteconfiguration_featured_next_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='featured_next_project',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='featured_next_projects',
            field=models.ManyToManyField(blank=True, help_text="Proyectos que rotan automáticamente en el banner 'EXPLORAR PROYECTO'. Usa la foto/video que cada proyecto ya tiene cargado en Portafolio. Vacío = se usa automáticamente el último proyecto activo.", related_name='+', to='core.portfolioproject', verbose_name="Proyectos destacados (banner 'Explorar Proyecto')"),
        ),
    ]
