# Generated by Django 5.2.13 on 2026-07-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_siteconfiguration_featured_next_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='cv_url',
            field=models.URLField(blank=True, help_text='Link de Dropbox o Drive al CV en PDF. Se previsualiza dentro del sitio, no se descarga.', max_length=500, verbose_name='CV (URL Dropbox/Drive)'),
        ),
    ]
