# Generated by Django 5.2.13 on 2026-07-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_teammember_cv_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='parallax_image_url',
            field=models.URLField(blank=True, help_text="Imagen grande de fondo sobre la sección 'QUÉ HICIMOS'. Se usa si no hay video.", max_length=500, verbose_name="Imagen parallax ('Qué Hicimos')"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='parallax_video_url',
            field=models.URLField(blank=True, help_text="Video de fondo sobre la sección 'QUÉ HICIMOS' (tiene prioridad sobre la imagen).", max_length=500, verbose_name="Video parallax ('Qué Hicimos')"),
        ),
    ]
