# Generated by Django 5.2.13 on 2026-07-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_siteconfiguration_parallax_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='parallax_projects',
            field=models.ManyToManyField(blank=True, help_text='Si eliges proyectos, sus fotos/videos rotan automáticamente como fondo en lugar de la imagen/video fijos de arriba.', related_name='+', to='core.portfolioproject', verbose_name="Proyectos rotando (parallax 'Qué Hicimos')"),
        ),
    ]
