# Generated by Django 5.2.13 on 2026-07-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_siteconfiguration_parallax_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='tipo',
            field=models.CharField(choices=[('noticia', 'NOTICIA'), ('charla', 'CHARLA'), ('premio', 'PREMIO'), ('publicacion', 'PUBLICACIÓN'), ('concurso', 'CONCURSO'), ('entrevista', 'ENTREVISTA'), ('otro', 'OTRO')], default='noticia', max_length=20, verbose_name='Tipo'),
        ),
    ]
