# Generated by Django 5.2.13 on 2026-07-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_mediaitem_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Título (EN)')),
                ('description', models.TextField(blank=True, verbose_name='Descripción breve')),
                ('description_en', models.TextField(blank=True, verbose_name='Descripción breve (EN)')),
                ('pdf_url', models.URLField(help_text='Link de Dropbox o Drive al PDF. Se previsualiza dentro del sitio en alta calidad, no se descarga.', max_length=500, verbose_name='PDF (URL Dropbox/Drive)')),
                ('cover_image_url', models.URLField(blank=True, help_text='Imagen para la tarjeta. Opcional — si se deja vacío se muestra un ícono genérico.', max_length=500, verbose_name='Imagen de portada (URL Cloudinary)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Documento de Portafolio',
                'verbose_name_plural': 'Portafolio (PDFs)',
                'ordering': ['order'],
            },
        ),
    ]
