# Generated by Django 5.2.13 on 2026-07-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_portfoliodocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodocument',
            name='pdf_size',
            field=models.BigIntegerField(blank=True, default=0, editable=False, help_text='Se calcula automáticamente al guardar.', verbose_name='Tamaño del PDF (bytes)'),
        ),
    ]
