# Generated by Django 5.2.13 on 2026-07-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_portfoliodocument_pdf_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='URL YouTube'),
        ),
    ]
