# Generated by Django 6.0.7 on 2026-07-22 00:19

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_siteconfiguration_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumitem',
            name='description',
            field=core.fields.RichTextField(blank=True, help_text='Texto de resumen mostrado bajo el subtítulo (ej: resumen de un documento adjunto).', verbose_name='Resumen'),
        ),
        migrations.AlterField(
            model_name='curriculumitem',
            name='description_en',
            field=core.fields.RichTextField(blank=True, verbose_name='Resumen (EN)'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='description',
            field=core.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='description_en',
            field=core.fields.RichTextField(blank=True, verbose_name='Descripción (EN)'),
        ),
        migrations.AlterField(
            model_name='mediaitemsection',
            name='body',
            field=core.fields.RichTextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='portfoliodocument',
            name='description',
            field=core.fields.RichTextField(blank=True, verbose_name='Descripción breve'),
        ),
        migrations.AlterField(
            model_name='portfoliodocument',
            name='description_en',
            field=core.fields.RichTextField(blank=True, verbose_name='Descripción breve (EN)'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description',
            field=core.fields.RichTextField(verbose_name='Descripción completa'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='description_en',
            field=core.fields.RichTextField(blank=True, verbose_name='Descripción completa (EN)'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='summary',
            field=core.fields.RichTextField(blank=True, help_text='Texto corto que aparece en la tarjeta del portafolio. Si se deja vacío se usan los primeros 280 caracteres de la descripción.', verbose_name='Resumen (tarjeta)'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='summary_en',
            field=core.fields.RichTextField(blank=True, verbose_name='Resumen (tarjeta EN)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_p1',
            field=core.fields.RichTextField(default='Cuatro volúmenes dibujan su órbita en torno a un vacío central que actúa como corazón del proyecto. La luz natural penetra desde múltiples ángulos, creando una danza de sombras que transforma el espacio a lo largo del día.', verbose_name='Párrafo 1 (Sobre)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_p1_en',
            field=core.fields.RichTextField(blank=True, verbose_name='Párrafo 1 (Sobre) (EN)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_p2',
            field=core.fields.RichTextField(default='Las fachadas están marcadas por una rigurosa modulación que refleja la precisión técnica del proceso constructivo. Cada detalle ha sido pensado para que la obra dialogue con su entorno y perdure en el tiempo.', verbose_name='Párrafo 2 (Sobre)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_p2_en',
            field=core.fields.RichTextField(blank=True, verbose_name='Párrafo 2 (Sobre) (EN)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='trust_sub',
            field=core.fields.RichTextField(default='Agradecemos profundamente la confianza de nuestros clientes, cuya visión y colaboración han sido fundamentales para crear proyectos que transforman espacios y comunidades.', verbose_name='Colaboradores — subtítulo'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='trust_sub_en',
            field=core.fields.RichTextField(blank=True, verbose_name='Colaboradores — subtítulo (EN)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=core.fields.RichTextField(blank=True, verbose_name='Descripción breve'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio_en',
            field=core.fields.RichTextField(blank=True, verbose_name='Descripción breve (EN)'),
        ),
    ]
