# Generated by Django 6.0.7 on 2026-07-22 01:10

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_curriculumitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herovideo',
            name='title_line1',
            field=core.fields.RichTextField(blank=True, help_text='Primera línea del título sobre el video (dejar en blanco para ocultar)'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='title_line1_en',
            field=core.fields.RichTextField(blank=True, help_text='Primera línea del título (EN)'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='title_line2',
            field=core.fields.RichTextField(blank=True, help_text='Segunda línea del título'),
        ),
        migrations.AlterField(
            model_name='herovideo',
            name='title_line2_en',
            field=core.fields.RichTextField(blank=True, help_text='Segunda línea del título (EN)'),
        ),
    ]
